# Generated by Django 5.0.1 on 2024-02-08 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srmsApp', '0008_subject_credit_alter_student_subject_result_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='code',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
    ]
